### ISSUE TITLE
Update Locations Database to Relational System (after I finish making it)

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#47]
Use the new excel file "UBHub Database Feb 2018"
It has a tab for each spreadsheet, as follows:
1. institutionsTable lists each location as a row and their basic attributes, including the id that the other tables use to reference each location.  Each one makes a map marker and popup basic attributes.
2. documentsTable has each activity/document as a row and often has multiple entries for each location.  This data will be used to populate filters, activity highlights, and the map popups
3. participationTable has each program with the locations as participants in rows.  the locations may repeat, but not within a program.  THis data will populate the program filters, highlights, and map popups.
4. mapbuttonTable summarizes the participationTable information in order to automate the highlight buttons for the map.
5. original_data is old and just for reference
6. resources_old is also old and just for reference

**Comment by joshuacassidygrant** [comment]
done, thanks
