### ISSUE TITLE
Add Jesse McKenna as a collaborator!

### ISSUE THREAD

**Issue by av2335** [glenpierce/UBHub#50]
She has a pull request ready to go for the About Us page.

jesse.e.mckenna@gmail.com

**Comment by glenpierce** [comment]
@av2335 does she have a github account? I tried to add her and Github says there's no one with an account matching that email address.

**Comment by av2335** [comment]
https://github.com/jessemckenna

**Comment by glenpierce** [comment]
Must be linked to a different email address. Welcome aboard Jesse!
