### ISSUE TITLE
Traffic lights Style Charts

### ISSUE THREAD

**Issue by glenpierce** [glenpierce/UBHub#58]
Instead of bars on the charts, we replace that data with just these circles above the labels. There would be no axis.

**Comment by glenpierce** [comment]
Both chart types

**Comment by glenpierce** [comment]
https://www.figma.com/file/ZbNEsn0f8vn9xcDbjvT3AtoL/Untitled?node-id=0%3A1

**Comment by paradalis** [comment]
THis is a duplicate entry with UBIF-0001 Traffic Light Style Charts
