### ISSUE TITLE
UBIF-0007 Add a delete feature to habitats, taxa, sites

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#66]
Include an ability to delete any erroneous habitats, taxa, or sites (polygons) on the UBIF 2.0 Project page.

**Comment by glenpierce** [comment]
@paradalis I suspect we will want to break this issue into 3 separate pieces, one for habitats, one for taxa, and one for sites.

**Comment by paradalis** [comment]
Ok, that is fine, but bear in mind that Rebecca did specifically request this feature so we should no neglect it.
