### ISSUE TITLE
UBIF-0008 Accept multiple iNaturalist Projects

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#68]
Imitate the same visual feedback when adding an iNaturalist project as used for the "add a habitat" method previously used on the same page.  This will also allow for multiple projects to be added to a single UBIF 2.O program.

**Comment by glenpierce** [comment]
![UBIF-0008 spec](https://user-images.githubusercontent.com/6483714/58929912-1ac63500-870e-11e9-8558-252a2e5b6959.PNG)

**Comment by glenpierce** [comment]
Two phases:
1: initial ui: add import like add habitat
2: add status to each import
