### ISSUE TITLE
UBIF-0009 Step 2 Time Frame

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#69]
Add the time frame feature to the Data Entry section of the website. 

Step 2. Indicate time frame:
User chooses whether the data will be analyzed by year or month. Then they will enter the year(s) or month(s) of interest. For example, they choose “Year” and then say years 2010 and 2015 are of interest. Or, they choose “Month” and then say Nov-Dec 2017 and March-April 2018 are of interest. Maximum of 5 time frames.

**Comment by glenpierce** [comment]
I'm now storing the data that the user enters and filtering out the observations that aren't within the date range.
