### ISSUE TITLE
UBIF-0010 Step 3: Verify Data

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#70]
After importing data, there needs to be a new set of tables here. First, the user should select the relevant habitat type. Then, a table will load with all the surrogate species for that habitat as rows (for the indicated time frame from step 2), and all the sites (polygons) as columns.

The table cells should autopopulate with the current observations, and allow the user to verify. This data should then be saved within our project instance for the time frame indicated.

**Comment by glenpierce** [comment]
This is this section of the page:
Step 3. Verify data:
Display the map of polygons and a table of the species for each polygon (select one at a time). User goes through one place/polygon at a time, and can click buttons in the species table for the user to verify presence/absence. Data is to be verified separately for each time frame.
