### ISSUE TITLE
UBIF-0011  Set up Step 4 Set Targets

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#71]
Step 4: Set targets

Allows the user to input percentage targets for each taxa and each habitat. SHould allow for "ok" (yellow) and "good" (green) levels. Should allow for both positive and negative goals (negative is for invasive taxa groups).

**Comment by glenpierce** [comment]
Allowing for both positive and negative goals (negative is for invasive taxa groups) is to support eventual features, we should develop with this in mind, but it does not need to be supported immediately.
