### ISSUE TITLE
UBIF-0012 Move Step 5 higher on page

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#72]
This part should be moved to just before the Data Entry section:

Step 5. Indicate surrogate species.
For each habitat type, choose the surrogate species you would like to track. If you have indicated a source of observations from above, species will auto-populate below and you will simply need to verify which ones you would like to include. Alternately, you can manually enter each surrogate species. Indicate the taxon of each species and then check the boxes to indicate which habitat you would like to consider for each surrogate species.

CSV upload part and the species table.

**Comment by glenpierce** [comment]
Fixed. Not Deployed yet.
