### ISSUE TITLE
UBIF-0013 UBIF Charts without targets

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#73]
Add charts to view status of the surrogate species data (Track 2) per the spec found here https://www.ubhub.org/statusReport

**Comment by glenpierce** [comment]
@paradalis This issue might make sense as the following set of issues:
**1. Create the basic chart template, this would include**
* coloring
* Y-Axis with labels as percents
* X-Axis with labels as Habitats or Taxa
* ticks
* the grey bar for missing / white for absent
**2 - 7. Create each of the tables**
* observations by taxa in all habitats
* observations by taxa over time
* all taxa in a selected habitat
* each species in a selected habitat of a selected taxon
* taxa by place
**8. Create table as seen on the bottom of this spec.**

**Comment by glenpierce** [comment]
That's 8 work units in 11 days from now... 😅

**Comment by paradalis** [comment]
ok. is that something I should do? not clear on the responsibilities here.
