### ISSUE TITLE
UBIF-0014 Table of surrogate species data

### ISSUE THREAD

**Issue by paradalis** [glenpierce/UBHub#74]
Auto-generate a table summarizing the species data over time as shown on the bottom of this page: https://www.ubhub.org/statusReport. 

There should be a drop down menu to choose the habitat type, and the table will rebuild for each habitat.

**Comment by glenpierce** [comment]
![UBIF-0014](https://user-images.githubusercontent.com/6483714/58930678-41399f80-8711-11e9-98f1-cc991240b311.PNG)
